"""create initial schema and mess ratings

Revision ID: 688121342025
Revises: 
Create Date: 2026-10-03 04:29:36.221409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '688121342025'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('available_today', sa.Boolean(), nullable=False),
    sa.Column('arrival_time', sa.String(length=10), nullable=True),
    sa.Column('leave_time', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('breakfast', sa.String(length=255), nullable=False),
    sa.Column('lunch', sa.String(length=255), nullable=False),
    sa.Column('snacks', sa.String(length=255), nullable=False),
    sa.Column('dinner', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day', name='unique_day')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_medical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('prescribed_medicine', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('room_no', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('room_number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('voters', sa.Text(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.String(length=20), nullable=False),
    sa.Column('menu_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_date', 'meal_type', name='unique_meal_menu_per_service')
    )
    with op.batch_alter_table('meal_menu', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_menu_service_date'), ['service_date'], unique=False)

    op.create_table('worker_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('worker_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('meal_rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_menu_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name='meal_rating_between_one_and_five'),
    sa.ForeignKeyConstraint(['meal_menu_id'], ['meal_menu.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meal_menu_id', 'user_id', name='unique_rating_per_student_meal')
    )
    with op.batch_alter_table('meal_rating', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meal_rating_meal_menu_id'), ['meal_menu_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meal_rating_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_rating', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_rating_user_id'))
        batch_op.drop_index(batch_op.f('ix_meal_rating_meal_menu_id'))

    op.drop_table('meal_rating')
    op.drop_table('worker_info')
    with op.batch_alter_table('meal_menu', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meal_menu_service_date'))

    op.drop_table('meal_menu')
    op.drop_table('issue')
    op.drop_table('user')
    op.drop_table('student_medical')
    op.drop_table('notice')
    op.drop_table('mess')
    op.drop_table('doctor')
    op.drop_table('bus_timetable')
    # ### end Alembic commands ###
